# ============================================================================
# Data Sources
# ============================================================================

# Elasticsearch CA Certificate
# Read the CA certificate from the local filesystem for TLS verification
# The certificate is generated by scripts/elk/00_create-certs.sh during deployment.
data "local_file" "elasticsearch_ca_cert" {
  filename = abspath("${path.module}/../../certs/ca/ca.crt")
}

