---
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: vault-stack
  labels:
    app: vault
spec:
  type: ClusterIP
  selector:
    app: vault
  ports:
  - name: http
    port: 8200
    targetPort: 8200
    protocol: TCP
  - name: cluster
    port: 8201
    targetPort: 8201
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: vault-external
  namespace: vault-stack
  labels:
    app: vault
spec:
  type: NodePort
  selector:
    app: vault
  ports:
  - name: http
    port: 8200
    targetPort: 8200
    nodePort: 30820
    protocol: TCP