# Note: These are placeholder secrets. In production, use sealed-secrets, external-secrets, or similar solutions.
# Base64 encode your actual values: echo -n "your-value" | base64
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-license
  namespace: vault-stack
type: Opaque
data:
  # Replace with your actual Vault Enterprise license (base64 encoded)
  license: REPLACE_WITH_BASE64_ENCODED_VAULT_LICENSE
---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-credentials
  namespace: vault-stack
type: Opaque
data:
  # elastic:password123 (base64 encoded)
  elastic-password: cGFzc3dvcmQxMjM=
  # kibana_system:kibana_password123 (base64 encoded)
  kibana-password: a2liYW5hX3Bhc3N3b3JkMTIz
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
  namespace: vault-stack
type: Opaque
data:
  # admin:admin (base64 encoded)
  admin-user: YWRtaW4=
  admin-password: YWRtaW4=
---
apiVersion: v1
kind: Secret
metadata:
  name: xpack-encryption-keys
  namespace: vault-stack
type: Opaque
data:
  # fhjskloppd678ehkdfdlliverpoolfcr (base64 encoded)
  encryption-key: Zmhqc2tsb3BwZDY3OGVoa2RmZGxsaXZlcnBvb2xmY3I=