---
# VaultAuth defines how VSO authenticates to Vault
# This uses Kubernetes authentication method
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth
  namespace: vault-stack
spec:
  # Reference to the VaultConnection
  vaultConnectionRef: vault-connection

  # Authentication method - using Kubernetes
  method: kubernetes

  # Mount path where Kubernetes auth is enabled
  mount: kubernetes

  # Kubernetes-specific configuration
  kubernetes:
    # Role to use for authentication (created by Terraform)
    role: vso-role

    # Service account to use for authentication
    # Uses the default service account in this namespace
    serviceAccount: default

    # Audiences for the JWT token
    audiences:
      - vault
