---
# Demo web application that uses secrets synced by VSO
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: vault-stack
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      serviceAccountName: default
      containers:
        - name: webapp
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
          env:
            # Environment variables from webapp-secret (synced by VSO)
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: webapp-secret
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: webapp-secret
                  key: password

            # Environment variables from database-secret (synced by VSO)
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: db_host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: db_port
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: db_name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: db_password

          # Volume mounts for secrets as files
          volumeMounts:
            - name: webapp-secret-volume
              mountPath: /etc/secrets/webapp
              readOnly: true
            - name: database-secret-volume
              mountPath: /etc/secrets/database
              readOnly: true
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
              readOnly: true

          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi

      volumes:
        # Mount webapp secret as files
        - name: webapp-secret-volume
          secret:
            secretName: webapp-secret

        # Mount database secret as files
        - name: database-secret-volume
          secret:
            secretName: database-secret

        # Custom nginx configuration to display environment variables
        - name: nginx-config
          configMap:
            name: webapp-nginx-config

---
# ConfigMap for nginx configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-nginx-config
  namespace: vault-stack
data:
  default.conf: |
    server {
        listen 80;
        server_name _;

        location / {
            default_type text/html;
            return 200 '<!DOCTYPE html>
    <html>
    <head>
        <title>VSO Application</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                max-width: 800px;
                margin: 50px auto;
                padding: 20px;
                background-color: #f5f5f5;
            }
            .container {
                background-color: white;
                border-radius: 8px;
                padding: 30px;
                box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            }
            h1 {
                color: #333;
                border-bottom: 3px solid #00d4aa;
                padding-bottom: 10px;
            }
            h2 {
                color: #555;
                margin-top: 30px;
            }
            .secret-section {
                background-color: #f9f9f9;
                border-left: 4px solid #00d4aa;
                padding: 15px;
                margin: 15px 0;
            }
            .secret-item {
                margin: 10px 0;
                font-family: monospace;
            }
            .label {
                font-weight: bold;
                color: #666;
            }
            .value {
                color: #00d4aa;
            }
            .info {
                background-color: #e3f2fd;
                border-left: 4px solid #2196f3;
                padding: 15px;
                margin: 20px 0;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🔐 Vault Secrets Operator Demo</h1>

            <div class="info">
                <strong>ℹ️ About this demo:</strong><br>
                This application demonstrates HashiCorp Vault Secrets Operator (VSO) synchronising secrets from Vault to Kubernetes. The secrets below are automatically synced from Vault and injected into this pod as environment variables.
            </div>

            <h2>📝 Web Application Credentials</h2>
            <div class="secret-section">
                <div class="secret-item">
                    <span class="label">Username:</span> <span class="value">$USERNAME</span>
                </div>
                <div class="secret-item">
                    <span class="label">Password:</span> <span class="value">$PASSWORD</span>
                </div>
            </div>

            <h2>🗄️ Database Configuration</h2>
            <div class="secret-section">
                <div class="secret-item">
                    <span class="label">Host:</span> <span class="value">$DB_HOST</span>
                </div>
                <div class="secret-item">
                    <span class="label">Port:</span> <span class="value">$DB_PORT</span>
                </div>
                <div class="secret-item">
                    <span class="label">Database:</span> <span class="value">$DB_NAME</span>
                </div>
                <div class="secret-item">
                    <span class="label">Username:</span> <span class="value">$DB_USERNAME</span>
                </div>
                <div class="secret-item">
                    <span class="label">Password:</span> <span class="value">$DB_PASSWORD</span>
                </div>
            </div>

            <div class="info">
                <strong>🔄 Try this:</strong><br>
                1. Update the secrets in Vault using <code>vault kv put</code><br>
                2. Wait up to 30 seconds<br>
                3. Refresh this page to see the updated values
            </div>
        </div>
    </body>
    </html>';
        }

        location /health {
            return 200 'OK';
            add_header Content-Type text/plain;
        }
    }

---
# Service to expose the webapp
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: vault-stack
  labels:
    app: webapp
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: webapp
