version: '3'

vars:
  NAMESPACE: vault-stack
  RELEASE_NAME: vault-stack
  CHART_PATH: ./helm-chart/vault-stack
  VAULT_POD: vault-0

tasks:
  # Main deployment command (Terraform)
  up:
    desc: Deploy the entire Vault stack using Terraform
    deps:
      - pre-deploy-checks
    cmds:
      - ./scripts/10_deploy_infra.sh

  # Initialise Vault
  init:
    desc: Initialise Vault
    cmds:
      - NAMESPACE={{.NAMESPACE}} VAULT_POD={{.VAULT_POD}} ./scripts/30_vault_init.sh

  # Unseal Vault
  unseal:
    desc: Unseal Vault and set up port forwarding
    cmds:
      - NAMESPACE={{.NAMESPACE}} VAULT_POD={{.VAULT_POD}} ./scripts/40_vault_unseal.sh
      - NAMESPACE={{.NAMESPACE}} ./scripts/20_port_forwarding.sh

  # Clean/destroy everything (Terraform)
  clean:
    desc: Destroy the entire stack using Terraform
    aliases: [rm]
    cmds:
      - NAMESPACE={{.NAMESPACE}} ./scripts/tools/destroy.sh

  # Show status of all components
  status:
    desc: Show status of all components
    cmds:
      - NAMESPACE={{.NAMESPACE}} VAULT_POD={{.VAULT_POD}} ./scripts/tools/status.sh

  # Access info
  info:
    desc: Show access information and credentials
    cmds:
      - ./scripts/tools/info.sh

  # Logs for a service
  logs:
    desc: View logs for a service
    cmds:
      - NAMESPACE={{.NAMESPACE}} ./scripts/tools/logs.sh {{.CLI_ARGS}}

  # Enable audit log collection in ELK
  audit:
    desc: Enable Vault audit log collection in ELK (Fleet integration)
    cmds:
      - ./scripts/50_vault_elk_integration.sh

  # Internal: Pre-deployment checks
  pre-deploy-checks:
    desc: "[Internal] Check if required tools are installed"
    cmds:
      - ./scripts/tools/pre-deploy-checks.sh

  # Help - show available commands
  default:
    desc: Show available commands
    cmds:
      - task --list
    silent: true