version: '3'

vars:
  NAMESPACE: vault-stack
  RELEASE_NAME: vault-stack
  CHART_PATH: ./helm-chart/vault-stack
  VAULT_POD: vault-stack-0

tasks:
  # Main deployment command (Terraform)
  up:
    desc: Deploy the entire Vault stack using Terraform
    aliases: [infra]
    deps:
      - pre-deploy-checks
    cmds:
      - ./scripts/10_deploy_infra.sh

  # Initialise Vault
  init:
    desc: Initialise Vault
    cmds:
      - NAMESPACE={{.NAMESPACE}} VAULT_POD={{.VAULT_POD}} ./scripts/30_vault_init.sh

  # Unseal Vault
  unseal:
    desc: Unseal Vault and set up port forwarding
    cmds:
      - NAMESPACE={{.NAMESPACE}} VAULT_POD={{.VAULT_POD}} ./scripts/40_vault_unseal.sh
      - NAMESPACE={{.NAMESPACE}} ./scripts/20_port_forwarding.sh

  # Configure Vault audit logging and Fleet integration
  audit:
    desc: Configure Vault audit logging and Fleet integration with ELK
    cmds:
      - NAMESPACE={{.NAMESPACE}} VAULT_POD={{.VAULT_POD}} ./scripts/50_vault_configure_audit.sh

  # Create sample data in Vault
  sample-data:
    desc: Create sample data in Vault (secrets, auth methods, policies)
    aliases: [data]
    cmds:
      - NAMESPACE={{.NAMESPACE}} VAULT_POD={{.VAULT_POD}} ./scripts/60_vault_sample_data.sh

  # VSO: Set up Vault Secrets Operator demo
  vso:
    desc: Deploy and configure Vault Secrets Operator (run after init & unseal)
    cmds:
      - NAMESPACE={{.NAMESPACE}} ./scripts/vso/00_deploy_vso.sh

  # VSO: Update secrets to test synchronisation
  vso-update:
    desc: Update secrets in Vault to test VSO sync
    cmds:
      - |
        echo "Updating secrets in Vault..."
        kubectl exec -n {{.NAMESPACE}} {{.VAULT_POD}} -- vault kv put kvv2/webapp/config \
          username="user-$(date +%s)" \
          password="pass-$(date +%s)"
        echo "Secret updated! VSO will sync within 30 seconds."
        echo "Use 'task info' to view updated credentials"

  # ELK Demo Namespace
  elk:
    desc: ELK demos (static & dynamic credentials) - Show available commands
    cmds:
      - task --list | grep "elk:"

  elk:static:
    desc: Deploy Elasticsearch static secrets demo (run after init & unseal)
    aliases: [static]
    cmds:
      - NAMESPACE={{.NAMESPACE}} ./scripts/elk/10_static_secrets.sh

  elk:dynamic:
    desc: Deploy Elasticsearch dynamic credentials demo (run after init & unseal)
    aliases: [dynamic]
    cmds:
      - NAMESPACE={{.NAMESPACE}} ./scripts/elk/20_dynamic_secrets.sh

  # Clean/destroy everything (Terraform)
  clean:
    desc: Destroy the entire stack
    aliases: [rm]
    cmds:
      - NAMESPACE={{.NAMESPACE}} ./scripts/tools/destroy.sh

  # Show status of all components
  status:
    desc: Show status of all components
    cmds:
      - NAMESPACE={{.NAMESPACE}} VAULT_POD={{.VAULT_POD}} ./scripts/tools/status.sh

  # Access info
  info:
    desc: Show access information and credentials
    cmds:
      - ./scripts/tools/info.sh

  # Logs for a service
  logs:
    desc: View logs for a service
    cmds:
      - NAMESPACE={{.NAMESPACE}} ./scripts/tools/logs.sh {{.CLI_ARGS}}

  # Internal: Pre-deployment checks
  pre-deploy-checks:
    desc: "[Internal] Check if required tools are installed"
    cmds:
      - ./scripts/tools/pre-deploy-checks.sh

  # Help - show available commands
  default:
    desc: Show available commands
    cmds:
      - task --list
    silent: true