# Prometheus Configuration (official chart)
prometheus:
  enabled: true

  server:
    enabled: true

    persistentVolume:
      enabled: true
      size: 10Gi

    resources:
      requests:
        memory: 512Mi
        cpu: 500m
      limits:
        memory: 1Gi
        cpu: 1000m

  alertmanager:
    enabled: false

  kube-state-metrics:
    enabled: true

  prometheus-node-exporter:
    enabled: true

  prometheus-pushgateway:
    enabled: false
