# Prometheus configuration
prometheus:
  enabled: true
  image:
    repository: prom/prometheus
    tag: "v2.48.0"
    pullPolicy: IfNotPresent

  replicas: 1

  config:
    scrapeInterval: 15s
    evaluationInterval: 15s

  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

  service:
    type: ClusterIP
    port: 9090

  persistence:
    enabled: true
    size: 10Gi
    storageClass: ""
