{{- if .Values.elasticsearch.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: elasticsearch-setup-passwords
  namespace: {{ .Values.global.namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  ttlSecondsAfterFinished: 120
  backoffLimit: 10
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: setup-passwords
        image: curlimages/curl:8.5.0
        command:
        - /bin/sh
        - -c
        - |
          set -e
          echo "Waiting for Elasticsearch to be ready..."
          until curl -k -u "elastic:password123" -s -f https://elasticsearch:9200/_cluster/health > /dev/null 2>&1; do
            echo "Elasticsearch not ready yet, waiting..."
            sleep 5
          done

          echo "Elasticsearch is ready. Setting up kibana_system password..."
          curl -k -u "elastic:password123" \
            -X POST "https://elasticsearch:9200/_security/user/kibana_system/_password" \
            -H "Content-Type: application/json" \
            -d '{"password":"kibana_password123"}'

          echo ""
          echo "Password setup complete!"
{{- end }}
