{{- if .Values.elasticsearch.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: {{ .Values.global.namespace }}
  labels:
    app: elasticsearch
spec:
  type: {{ .Values.elasticsearch.service.type }}
  selector:
    app: elasticsearch
  ports:
  - name: http
    port: {{ .Values.elasticsearch.service.httpPort }}
    targetPort: 9200
    protocol: TCP
  - name: transport
    port: {{ .Values.elasticsearch.service.transportPort }}
    targetPort: 9300
    protocol: TCP
{{- end }}