{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ .Values.global.namespace }}
  labels:
    app: grafana
spec:
  type: {{ .Values.grafana.service.type }}
  selector:
    app: grafana
  ports:
  - name: http
    port: {{ .Values.grafana.service.port }}
    targetPort: 3000
    protocol: TCP
{{- end }}