{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: {{ .Values.global.namespace }}
  labels:
    app: prometheus
spec:
  type: {{ .Values.prometheus.service.type }}
  selector:
    app: prometheus
  ports:
  - name: http
    port: {{ .Values.prometheus.service.port }}
    targetPort: 9090
    protocol: TCP
{{- end }}