{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: {{ .Values.global.namespace }}
data:
  prometheus.yml: |
    scrape_configs:
      - job_name: vault
        metrics_path: /v1/sys/metrics
        scheme: http
        static_configs:
        - targets: ['vault:8200']
{{- end }}