{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  vault-root-user-password: {{ .Values.secrets.redis.vaultRootUserPassword }}
  vault-dynamic-user-password: {{ .Values.secrets.redis.vaultDynamicUserPassword }}
  vault-static-user1-password: {{ .Values.secrets.redis.vaultStaticUser1Password }}
  vault-static-user2-password: {{ .Values.secrets.redis.vaultStaticUser2Password }}
  vault-static-user3-password: {{ .Values.secrets.redis.vaultStaticUser3Password }}
  vault-static-user4-password: {{ .Values.secrets.redis.vaultStaticUser4Password }}
{{- end }}
