{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Values.global.namespace }}
  labels:
    app: redis
spec:
  type: {{ .Values.redis.service.type }}
  selector:
    app: redis
  ports:
  - name: redis
    port: {{ .Values.redis.service.port }}
    targetPort: 6379
    protocol: TCP
{{- end }}