{{- if .Values.redis.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: {{ .Values.global.namespace }}
data:
  redis-users.conf: |
    # redis.conf

    # Enable ACL support
    user default off
    # Create vault-root-user with full permissions and a password
    user vault-root-user on >${VAULT_ROOT_USER_PASSWORD} ~* +@all
    # Create other Redis users (static users)
    user vault-dynamic-user on >${VAULT_DYNAMIC_USER_PASSWORD} ~* +@all
    user vault-static-user-1 on >${VAULT_STATIC_USER_1_PASSWORD} ~* +@all
    user vault-static-user-2 on >${VAULT_STATIC_USER_2_PASSWORD} ~* +@all
    user vault-static-user-3 on >${VAULT_STATIC_USER_3_PASSWORD} ~* +@all
    user vault-static-user-4 on >${VAULT_STATIC_USER_4_PASSWORD} ~* +@all
{{- end }}