{{- if .Values.vault.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: vault-license
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  license: {{ .Values.secrets.vault.license }}
  token: {{ .Values.secrets.vault.token }}
{{- end }}
