# ============================================================================
# Data Sources
# ============================================================================

# Elasticsearch CA Certificate
# Read the CA certificate from the local filesystem for TLS verification
#
# Note: Currently set to insecure=true in the connection below, so this is
# available for future use if we want to enable proper TLS verification.
# The certificate is generated by scripts/elk/00_create-certs.sh during deployment.
data "local_file" "elasticsearch_ca_cert" {
  filename = abspath("${path.module}/../certs/ca/ca.crt")
}

# ============================================================================
# Vault Policy for Dynamic Credentials
# ============================================================================

# Create policy document for reading dynamic credentials
data "vault_policy_document" "elasticsearch_dynamic" {
  rule {
    path         = "${vault_mount.database.path}/creds/${vault_database_secret_backend_role.elasticsearch.name}"
    capabilities = ["read"]
    description  = "Allow reading dynamic Elasticsearch credentials"
  }

  rule {
    path         = "${vault_mount.database.path}/creds/*"
    capabilities = ["list"]
    description  = "Allow listing database credential paths"
  }
}
