apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: vault-stack
  labels:
    app: loki
spec:
  type: ClusterIP
  selector:
    app: loki
  ports:
  - name: http
    port: 3100
    targetPort: 3100
    protocol: TCP
  - name: grpc
    port: 9096
    targetPort: 9096
    protocol: TCP