apiVersion: v2
name: vault-stack
description: A Helm chart for Vault Enterprise with ELK and monitoring stack using official upstream charts
type: application
version: 2.0.0
appVersion: "1.20"
keywords:
  - vault
  - elasticsearch
  - kibana
  - grafana
  - prometheus
  - loki
maintainers:
  - name: vault-stack-team

dependencies:
  # HashiCorp Vault Enterprise
  - name: vault
    version: "0.31.0"
    repository: "https://helm.releases.hashicorp.com"
    condition: vault.enabled
    alias: vault

  # Elastic Cloud on Kubernetes (ECK) Operator
  - name: eck-operator
    version: "2.10.0"
    repository: "https://helm.elastic.co"
    condition: eck-operator.enabled
    alias: eck-operator

  # Grafana
  - name: grafana
    version: "8.9.0"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled
    alias: grafana

  # Prometheus
  - name: prometheus
    version: "25.28.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled
    alias: prometheus

  # Loki
  - name: loki
    version: "6.27.0"
    repository: "https://grafana.github.io/helm-charts"
    condition: loki.enabled
    alias: loki

  # Promtail
  - name: promtail
    version: "6.16.6"
    repository: "https://grafana.github.io/helm-charts"
    condition: promtail.enabled
    alias: promtail