# Grafana configuration
grafana:
  enabled: true
  image:
    repository: grafana/grafana
    tag: "10.2.2"
    pullPolicy: IfNotPresent

  replicas: 1

  credentials:
    secretName: grafana-credentials
    adminUserKey: admin-user
    adminPasswordKey: admin-password

  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

  service:
    type: ClusterIP
    port: 3000

  persistence:
    enabled: true
    size: 5Gi
    storageClass: ""
