# Grafana Configuration (official chart)
grafana:
  enabled: true

  adminUser: admin
  adminPassword: admin

  persistence:
    enabled: true
    size: 5Gi

  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus-server:80
          isDefault: true
        - name: Loki
          type: loki
          url: http://loki:3100

# Grafana secrets configuration (base64 encoded)
secrets:
  grafana:
    adminUser: "YWRtaW4="
    adminPassword: "YWRtaW4="
