{{- if .Values.loki.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: {{ .Values.global.namespace }}
  labels:
    app: loki
spec:
  replicas: {{ .Values.loki.replicas }}
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      securityContext:
        fsGroup: 10001
      initContainers:
      - name: loki-permission-fix
        image: busybox:latest
        command: ['sh', '-c', 'chown -R 10001:10001 /loki/data && chmod -R 755 /loki/data']
        volumeMounts:
        - name: loki-data
          mountPath: /loki/data
      containers:
      - name: loki
        image: {{ .Values.loki.image.repository }}:{{ .Values.loki.image.tag }}
        imagePullPolicy: {{ .Values.loki.image.pullPolicy }}
        args:
        - -config.file=/etc/loki/loki.yml
        ports:
        - containerPort: {{ .Values.loki.service.port }}
          name: http
          protocol: TCP
        - containerPort: 9096
          name: grpc
          protocol: TCP
        volumeMounts:
        - name: loki-config
          mountPath: /etc/loki
          readOnly: true
        - name: loki-data
          mountPath: /loki/data
        livenessProbe:
          httpGet:
            path: /ready
            port: 3100
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 3100
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          {{- toYaml .Values.loki.resources | nindent 10 }}
      volumes:
      - name: loki-config
        configMap:
          name: loki-config
      - name: loki-data
        persistentVolumeClaim:
          claimName: loki-data-pvc
{{- end }}