{{- if .Values.loki.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: {{ .Values.global.namespace }}
  labels:
    app: loki
spec:
  type: {{ .Values.loki.service.type }}
  selector:
    app: loki
  ports:
  - name: http
    port: {{ .Values.loki.service.port }}
    targetPort: 3100
    protocol: TCP
  - name: grpc
    port: 9096
    targetPort: 9096
    protocol: TCP
{{- end }}