{{- if .Values.vault.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: {{ .Values.global.namespace }}
data:
  raft.hcl: |
    ui                = {{ .Values.vault.config.ui }}
    disable_mlock     = {{ .Values.vault.config.disableMlock }}
    default_lease_ttl = "{{ .Values.vault.config.defaultLeaseTtl }}"
    max_lease_ttl     = "{{ .Values.vault.config.maxLeaseTtl }}"

    api_addr          = "{{ .Values.vault.config.apiAddr }}"
    cluster_addr      = "{{ .Values.vault.config.clusterAddr }}"

    storage "raft" {
      path = "{{ .Values.vault.raft.path }}"
      node_id = "{{ .Values.vault.raft.nodeId }}"
    }

    listener "tcp" {
      address       = "{{ .Values.vault.listener.address }}"
      tls_disable   = "{{ if .Values.vault.listener.tlsDisable }}1{{ else }}0{{ end }}"
      telemetry {
        unauthenticated_metrics_access = {{ .Values.vault.telemetry.unauthenticatedMetricsAccess }}
      }
    }

    telemetry {
      disable_hostname = {{ .Values.vault.telemetry.disableHostname }}
      prometheus_retention_time = "{{ .Values.vault.telemetry.prometheusRetentionTime }}"
    }

    reporting {
        license {
            enabled = false
       }
    }
{{- end }}