{{- if .Values.vault.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
  namespace: {{ .Values.global.namespace }}
  labels:
    app: vault
spec:
  serviceName: vault
  replicas: {{ .Values.vault.replicas }}
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: vault-permission-fix
        image: busybox:latest
        command: ['sh', '-c', 'chown -R 1000:1000 /vault/file && chmod -R 755 /vault/file']
        volumeMounts:
        - name: vault-data
          mountPath: /vault/file
      containers:
      - name: vault
        image: {{ .Values.vault.image.repository }}:{{ .Values.vault.image.tag }}
        imagePullPolicy: {{ .Values.vault.image.pullPolicy }}
        command: ["vault", "server", "-config=/vault/config/raft.hcl"]
        env:
        - name: VAULT_ADDR
          value: "{{ .Values.vault.config.apiAddr }}"
        - name: VAULT_LICENSE
          valueFrom:
            secretKeyRef:
              name: {{ .Values.vault.license.secretName }}
              key: {{ .Values.vault.license.secretKey }}
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.vault.token.secretName }}
              key: {{ .Values.vault.token.secretKey }}
        - name: VAULT_LOG_LEVEL
          value: "{{ .Values.vault.config.logLevel }}"
        ports:
        - containerPort: 8200
          name: http
          protocol: TCP
        - containerPort: 8201
          name: cluster
          protocol: TCP
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
        volumeMounts:
        - name: vault-config
          mountPath: /vault/config
          readOnly: true
        - name: vault-data
          mountPath: /vault/file
        - name: vault-logs
          mountPath: /vault/logs
        livenessProbe:
          httpGet:
            path: /v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204
            port: 8200
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204
            port: 8200
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          {{- toYaml .Values.vault.resources | nindent 10 }}
      volumes:
      - name: vault-config
        configMap:
          name: vault-config
      - name: vault-data
        persistentVolumeClaim:
          claimName: vault-data-pvc
      - name: vault-logs
        persistentVolumeClaim:
          claimName: vault-logs-pvc
{{- end }}