---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: vault-stack
  labels:
    app: kibana
spec:
  type: ClusterIP
  selector:
    app: kibana
  ports:
  - name: http
    port: 5601
    targetPort: 5601
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-external
  namespace: vault-stack
  labels:
    app: kibana
spec:
  type: NodePort
  selector:
    app: kibana
  ports:
  - name: http
    port: 5601
    targetPort: 5601
    nodePort: 30561
    protocol: TCP