apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: vault-stack
  labels:
    app: promtail
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      serviceAccountName: promtail
      containers:
      - name: promtail
        image: docker.io/grafana/promtail:latest
        imagePullPolicy: IfNotPresent
        args:
        - -config.file=/etc/promtail/promtail.yml
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - containerPort: 9080
          name: http
          protocol: TCP
        volumeMounts:
        - name: promtail-config
          mountPath: /etc/promtail
          readOnly: true
        - name: promtail-data
          mountPath: /promtail
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: vault-logs
          mountPath: /mnt/vault-logs
          readOnly: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: promtail-config
        configMap:
          name: promtail-config
      - name: promtail-data
        persistentVolumeClaim:
          claimName: promtail-data-pvc
      - name: varlog
        hostPath:
          path: /var/log
          type: Directory
      - name: vault-logs
        persistentVolumeClaim:
          claimName: vault-logs-pvc
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail
  namespace: vault-stack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: promtail
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: promtail
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: promtail
subjects:
- kind: ServiceAccount
  name: promtail
  namespace: vault-stack